# Generated by Django 3.0.7 on 2020-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.TextField(max_length=50)),
                ('message_text', models.TextField()),
            ],
        ),
    ]
