# Generated by Django 3.0.7 on 2020-06-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message_title',
            new_name='title',
        ),
    ]
